# Edge TTS Voices (partial, for demo)
# For full list, see: https://github.com/rany2/edge-tts/blob/main/edge_tts/data/voices.json
# Format: language: [(voice_code, gender, display_name)]

# Expanded EDGE_TTS_VOICES for all 109 languages (single voice per language from languages.yaml)
EDGE_TTS_VOICES = {
    "English": [("en-US-AvaNeural", "Female", "Ava")],
    "Spanish": [("es-ES-ElviraNeural", "Female", "Elvira")],
    "French": [("fr-FR-DeniseNeural", "Female", "Denise")],
    "German": [("de-DE-KatjaNeural", "Female", "Katja")],
    "Italian": [("it-IT-IsabellaNeural", "Female", "Isabella")],
    "Portuguese": [("pt-BR-FranciscaNeural", "Female", "Francisca")],
    "Russian": [("ru-RU-DmitryNeural", "Male", "Dmitry")],
    "Japanese": [("ja-JP-NanamiNeural", "Female", "Nanami")],
    "Korean": [("ko-KR-SunHiNeural", "Female", "SunHi")],
    "Chinese (Simplified)": [("zh-CN-XiaoxiaoNeural", "Female", "Xiaoxiao")],
    "Chinese (Traditional)": [("zh-TW-HsiaoChenNeural", "Female", "HsiaoChen")],
    "Arabic": [("ar-SA-ZariyahNeural", "Female", "Zariyah")],
    "Hindi": [("hi-IN-SwatiNeural", "Female", "Swati")],
    "Bengali": [("bn-IN-TithiNeural", "Female", "Tithi")],
    "Telugu": [("te-IN-ValluvasalaNeural", "Female", "Valluvasala")],
    "Tamil": [("ta-IN-VeenaNeural", "Female", "Veena")],
    "Marathi": [("mr-IN-AnanyaNeural", "Female", "Ananya")],
    "Gujarati": [("gu-IN-AarohiNeural", "Female", "Aarohi")],
    "Turkish": [("tr-TR-EmelNeural", "Female", "Emel")],
    "Vietnamese": [("vi-VN-HoaiMyNeural", "Female", "HoaiMy")],
    "Polish": [("pl-PL-ZofiaNeural", "Female", "Zofia")],
    "Dutch": [("nl-NL-MayaNeural", "Female", "Maya")],
    "Swedish": [("sv-SE-SofieNeural", "Female", "Sofie")],
    "Greek": [("el-GR-AthinaNeural", "Female", "Athina")],
    "Czech": [("cs-CZ-VlastaNeural", "Female", "Vlasta")],
    "Hungarian": [("hu-HU-NoemiNeural", "Female", "Noemi")],
    "Romanian": [("ro-RO-AleaNeural", "Female", "Alea")],
    "Thai": [("th-TH-PremwadeeNeural", "Female", "Premwadee")],
    "Indonesian": [("id-ID-GadisNeural", "Female", "Gadis")],
    "Malayalam": [("ml-IN-AadhiNeural", "Male", "Aadhi")],
    "Ukrainian": [("uk-UA-OstapNeural", "Male", "Ostap")],
    "Afrikaans": [("af-ZA-WillemNeural", "Male", "Willem")],
    "Albanian": [("sq-AL-IlseNeural", "Female", "Ilse")],
    "Amharic": [("am-ET-MekdesNeural", "Female", "Mekdes")],
    "Armenian": [("hy-AM-AnahitNeural", "Female", "Anahit")],
    "Azerbaijani": [("az-AZ-BanuNeural", "Female", "Banu")],
    "Basque": [("eu-ES-AinhoaNeural", "Female", "Ainhoa")],
    "Belarusian": [("be-BY-NatashaSergeyevichNeural", "Female", "NatashaSergeyevich")],
    "Bulgarian": [("bg-BG-KrystalNeural", "Female", "Krystal")],
    "Catalan": [("ca-ES-JoanaNeural", "Female", "Joana")],
    "Welsh": [("cy-GB-NiaNeural", "Female", "Nia")],
    "Danish": [("da-DK-ChristelNeural", "Female", "Christel")],
    "Estonian": [("et-EE-AnuNeural", "Female", "Anu")],
    "Finnish": [("fi-FI-NooraNeural", "Female", "Noora")],
    "Galician": [("gl-ES-RosamariaNeural", "Female", "Rosamaria")],
    "Georgian": [("ka-GE-EkaNeural", "Female", "Eka")],
    "Hebrew": [("he-IL-HilaNeural", "Female", "Hila")],
    "Icelandic": [("is-IS-GudrunNeural", "Female", "Gudrun")],
    "Irish": [("ga-IE-OrlaNeural", "Female", "Orla")],
    "Latvian": [("lv-LV-EVITANeural", "Female", "EVITA")],
    "Lithuanian": [("lt-LT-LiepaNeural", "Female", "Liepa")],
    "Macedonian": [("mk-MK-MarijaNeural", "Female", "Marija")],
    "Norwegian": [("nb-NO-PernilleNeural", "Female", "Pernille")],
    "Persian": [("fa-IR-DilaNeural", "Female", "Dila")],
    "Slovak": [("sk-SK-VioletaNeural", "Female", "Violeta")],
    "Slovenian": [("sl-SI-PetraNeural", "Female", "Petra")],
    "Serbian": [("sr-RS-SophieNeural", "Female", "Sophie")],
}
