# Language constants and mappings
# Shared constants for language processing across the application

# Language name to ISO code mapping for analyzer registry
LANGUAGE_NAME_TO_CODE = {
    "English": "en",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Italian": "it",
    "Portuguese": "pt",
    "Russian": "ru",
    "Japanese": "ja",
    "Korean": "ko",
    "Chinese (Simplified)": "zh",
    "Chinese (Traditional)": "zh",
    "Arabic": "ar",
    "Hindi": "hi",
    "Bengali": "bn",
    "Telugu": "te",
    "Tamil": "ta",
    "Dutch": "nl",
    "Swedish": "sv",
    "Norwegian": "no",
    "Danish": "da",
    "Finnish": "fi",
    "Polish": "pl",
    "Czech": "cs",
    "Slovak": "sk",
    "Hungarian": "hu",
    "Romanian": "ro",
    "Bulgarian": "bg",
    "Greek": "el",
    "Turkish": "tr",
    "Hebrew": "he",
    "Thai": "th",
    "Vietnamese": "vi",
    "Indonesian": "id",
    "Malay": "ms",
    "Filipino": "fil",
    "Swahili": "sw",
    "Amharic": "am",
    "Hausa": "ha",
    "Yoruba": "yo",
    "Igbo": "ig",
    "Zulu": "zu",
    "Xhosa": "xh",
    "Afrikaans": "af",
    "Albanian": "sq",
    "Armenian": "hy",
    "Azerbaijani": "az",
    "Basque": "eu",
    "Belarusian": "be",
    "Bosnian": "bs",
    "Catalan": "ca",
    "Croatian": "hr",
    "Estonian": "et",
    "Galician": "gl",
    "Georgian": "ka",
    "Icelandic": "is",
    "Irish": "ga",
    "Kazakh": "kk",
    "Kyrgyz": "ky",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Macedonian": "mk",
    "Maltese": "mt",
    "Mongolian": "mn",
    "Montenegrin": "cnr",
    "Nepali": "ne",
    "Pashto": "ps",
    "Persian": "fa",
    "Serbian": "sr",
    "Slovenian": "sl",
    "Tajik": "tg",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Uzbek": "uz",
    "Welsh": "cy",
}